resource "aws_lambda_function" "api" {
  filename      = "lambda_function_payload.zip" # This will be generated by the build script
  function_name = "${var.project_name}-api"
  role          = aws_iam_role.lambda_role.arn
  handler       = "app.handler" # Mangum handler
  runtime       = "python3.11"
  timeout       = 30
  memory_size   = 512

  environment {
    variables = {
      GEMINI_API_KEY             = var.gemini_api_key
      GEMINI_MODEL_ID           = var.gemini_model_id
      DYNAMODB_TABLE_SCHEMES     = aws_dynamodb_table.schemes.name
      DYNAMODB_TABLE_USERS       = aws_dynamodb_table.users.name
      DYNAMODB_TABLE_CONVERSATIONS = aws_dynamodb_table.conversations.name
      DYNAMODB_TABLE_SUBMISSIONS = aws_dynamodb_table.submissions.name
      DYNAMODB_TABLE_EMBEDDINGS  = aws_dynamodb_table.embeddings.name
      S3_BUCKET_DOCUMENTS        = aws_s3_bucket.documents.id
      RAG_STORAGE_BACKEND        = "dynamodb"
    }
  }

  tags = local.common_tags
}

# CloudWatch Log Group for Lambda
resource "aws_cloudwatch_log_group" "lambda_log" {
  name              = "/aws/lambda/${aws_lambda_function.api.function_name}"
  retention_in_days = 14
}
